<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Cart\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.Added</code>
 */
class Added extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protobuf.Item item = 1;</code>
     */
    protected $item = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cart\ProtoBuf\Item $item
     * }
     */
    public function __construct($data = NULL) {
        \Cart\Metadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protobuf.Item item = 1;</code>
     * @return \Cart\ProtoBuf\Item|null
     */
    public function getItem()
    {
        return $this->item;
    }

    public function hasItem()
    {
        return isset($this->item);
    }

    public function clearItem()
    {
        unset($this->item);
    }

    /**
     * Generated from protobuf field <code>.protobuf.Item item = 1;</code>
     * @param \Cart\ProtoBuf\Item $var
     * @return $this
     */
    public function setItem($var)
    {
        GPBUtil::checkMessage($var, \Cart\ProtoBuf\Item::class);
        $this->item = $var;

        return $this;
    }

}

