<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Cart\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.Cleared</code>
 */
class Cleared extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protobuf.Items items = 1;</code>
     */
    protected $items = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cart\ProtoBuf\Items $items
     * }
     */
    public function __construct($data = NULL) {
        \Cart\Metadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protobuf.Items items = 1;</code>
     * @return \Cart\ProtoBuf\Items|null
     */
    public function getItems()
    {
        return $this->items;
    }

    public function hasItems()
    {
        return isset($this->items);
    }

    public function clearItems()
    {
        unset($this->items);
    }

    /**
     * Generated from protobuf field <code>.protobuf.Items items = 1;</code>
     * @param \Cart\ProtoBuf\Items $var
     * @return $this
     */
    public function setItems($var)
    {
        GPBUtil::checkMessage($var, \Cart\ProtoBuf\Items::class);
        $this->items = $var;

        return $this;
    }

}

