<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Cart\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.Paid</code>
 */
class Paid extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protobuf.Items items = 1;</code>
     */
    protected $items = null;
    /**
     * Generated from protobuf field <code>int64 shopperId = 2;</code>
     */
    protected $shopperId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cart\ProtoBuf\Items $items
     *     @type int|string $shopperId
     * }
     */
    public function __construct($data = NULL) {
        \Cart\Metadata\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protobuf.Items items = 1;</code>
     * @return \Cart\ProtoBuf\Items|null
     */
    public function getItems()
    {
        return $this->items;
    }

    public function hasItems()
    {
        return isset($this->items);
    }

    public function clearItems()
    {
        unset($this->items);
    }

    /**
     * Generated from protobuf field <code>.protobuf.Items items = 1;</code>
     * @param \Cart\ProtoBuf\Items $var
     * @return $this
     */
    public function setItems($var)
    {
        GPBUtil::checkMessage($var, \Cart\ProtoBuf\Items::class);
        $this->items = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 shopperId = 2;</code>
     * @return int|string
     */
    public function getShopperId()
    {
        return $this->shopperId;
    }

    /**
     * Generated from protobuf field <code>int64 shopperId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setShopperId($var)
    {
        GPBUtil::checkInt64($var);
        $this->shopperId = $var;

        return $this;
    }

}

