<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Calculator\Metadata\ProtoBuf;

class Event
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ï
event.protoprotobuf"
Added
result ("

Subtracted
result ("
Divided
result ("

Multiplied
result ("
ResetB5ÊCalculator\\ProtoBufâCalculator\\Metadata\\ProtoBufbproto3'
        , true);

        static::$is_initialized = true;
    }
}

