<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item.proto

namespace Cart\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.Items</code>
 */
class Items extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protobuf.Item items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Cart\ProtoBuf\Item>|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \Cart\Metadata\Item::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.Item items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.Item items = 1;</code>
     * @param array<\Cart\ProtoBuf\Item>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cart\ProtoBuf\Item::class);
        $this->items = $arr;

        return $this;
    }

}

